trigger:
  branches:
    include:
      - main   # Change branch if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_STORAGE_ACCOUNT: "storageaccountmdu001"
  TF_CONTAINER_NAME: "mdu-statefile"
  TF_STATE_FILE: "terraform.tfstate"
  TF_RESOURCE_GROUP: "rg-mdu-dev-001"

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'mdu-conn'
    KeyVaultName: 'kv-Mdu-dev-uksouth-001'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.9.8'   # Choose the version you want

- script: |
    terraform init \
      -backend-config="resource_group_name=$(TF_RESOURCE_GROUP)" \
      -backend-config="storage_account_name=$(TF_STORAGE_ACCOUNT)" \
      -backend-config="container_name=$(TF_CONTAINER_NAME)" \
      -backend-config="key=$(TF_STATE_FILE)"
  displayName: 'Terraform Init'

- script: terraform plan -out=tfplan
  displayName: 'Terraform Plan'
  env:
    ARM_CLIENT_ID: $(servicePrincipalId)
    ARM_CLIENT_SECRET: $(servicePrincipalKey)
    ARM_SUBSCRIPTION_ID: $(subscriptionId)
    ARM_TENANT_ID: $(tenantId)

- script: terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
  env:
    ARM_CLIENT_ID: $(servicePrincipalId)
    ARM_CLIENT_SECRET: $(servicePrincipalKey)
    ARM_SUBSCRIPTION_ID: $(subscriptionId)
    ARM_TENANT_ID: $(tenantId)
